version: 2
jobs:
  build:
    docker:
      # specify the NodeJS version you desire here
      - image: circleci/node:7.10
 
    working_directory: ~/repo
 
    steps:
      - checkout
 
      # Necessary to have Docker Engine within CircleCI
      - setup_remote_docker:
          docker_layer_caching: true
 
      # Download and cache dependencies
      # It is simply a time saver
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
 
      - run: npm install
 
      # Retrieve cache
      # It is simply a time saver
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
         
      # run tests
      - run: npm test
 
      # You can create environment variable to secure your credentials. See https://circleci.com/docs/2.0/env-vars/#declaring-environment-variables
      - run: docker login -u="remyma+circleci" -p="UGP6QB9VUPKCBV1L13V15K2SCXFFDKACP5RXM0VXGR29CZNOJVCZWVG51EFD8871" quay.io
 
      # build the application image
      - run: docker build -t remyma/node-openshift-ex .
 
      # Tag the image
      - run: docker tag remyma/node-openshift-ex quay.io/remyma/node-openshift-ex:latest
 
      # deploy the image
      - run: docker push quay.io/remyma/node-openshift-ex:latest
