version: 2
jobs:
  build:
    docker:
      # specify the NodeJS version you desire here
      - image: circleci/node:7.10
 
    working_directory: ~/repo
 
    steps:
      - checkout
 
      # Necessary to have Docker Engine within CircleCI
      - setup_remote_docker:
          docker_layer_caching: true
 
      # Download and cache dependencies
      # It is simply a time saver
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
 
      - run: npm install
 
      # Retrieve cache
      # It is simply a time saver
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
         
      # run tests
      - run: npm test

